version: "3.7"
services:
  air_quality_service_dev:
      build:
        context: .
      working_dir: /app
      env_file:
        - ./config/dev.env
      ports:
        - 3000:3000
      volumes:
        - .:/app
        - /app/node_modules
      depends_on:
        - postgres
      restart: always
  postgres:
    image: postgres:17.4-alpine3.21
    env_file:
      - ./config/dev.env
    ports: 
      - '5437:5432'
    volumes:
      - ~/pg_data/air_quality_dev:/var/lib/postgresql/data